# syntax=docker.io/docker/dockerfile:1.7-labs
FROM debian:bullseye

ARG VERSION

LABEL version="1.0"
LABEL maintainer="gang.liu"

COPY --exclude=**/s6 --exclude=**/yum.repos.d --exclude=**/*.tar.gz rootfs /

# set -eux;
SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]

# runtime dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
        tzdata \
        lsof \
        vim \
        telnet \
        net-tools \
        curl \
        tcpdump \
        openssl \
        ca-certificates \
        tini \
        procps \
        python3 \
   && rm -rf /var/lib/apt/lists/*

COPY --from=registry.k8s.io/pause:3.10 /pause /usr/bin/pause

ENTRYPOINT ["/usr/bin/tini", "-g", "-vv", "--"]

CMD ["python3", "-m", "http.server", "8080"]
