FROM debian:bullseye

ARG VERSION

LABEL version="1.0"
LABEL maintainer="gang.liu"

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
        tzdata \
        lsof \
        vim \
        telnet \
        net-tools \
        iproute \
        curl \
        tcpdump \
        openssl \
        ca-certificates \
        dumb-init \
   && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/bin/dumb-init", "--"]

CMD ["python2.7", "-m", "SimpleHTTPServer", "8080"]