FROM centos:centos7.9.2009

ARG VERSION

RUN yum install -y \
    tzdata \
    lsof \
    vim \
    telnet \
    net-tools \
    iproute \
    curl \
    tcpdump \
    openssl \
    ca-certificates \
    ;

# s6 overlay
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.1/s6-overlay-amd64-installer /tmp/
RUN chmod +x /tmp/s6-overlay-amd64-installer && /tmp/s6-overlay-amd64-installer /

ENTRYPOINT ["/init"]
CMD ["python2.7", "-m", "SimpleHTTPServer", "8080"]