FROM rockylinux:8.9.20231119

RUN dnf update -y \
 && dnf install -y \
        bzip2 \
        curl \
        file \
        findutils \
        gcc-c++ \
        gcc \
        gcc-gfortran \
        git \
        gnupg2 \
        hg \
        hostname \
        iproute \
        make \
        patch \
        python3 \
        python3-pip \
        python3-setuptools \
        svn \
        unzip \
        xz \
        zstd \
 && rm -rf /var/cache/dnf \
 && dnf clean all