#!/usr/bin/env bash

#ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -N ""
#ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ""
#ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ""

#sed -i 's/GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
#sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
#sed -i 's/UseDNS yes/UseDNS no/g' /etc/ssh/sshd_config
#echo test@2024ABC | passwd --stdin root

/usr/sbin/sshd -D